### PR TITLE
feat: Delete article content type

### PR DESCRIPTION
**Pull request by attiks**
Refs: HRINFO-1175

### CODE REVIEW

**Comment by attiks** [comment]
Blocked by https://github.com/UN-OCHA/hrinfo-site-2022/pull/58

**Review by rupl — APPROVED** [review]
I used the bulk ops to delete all "Article (deprecated)" nodes and it seems to unblock the config import.

**Comment by attiks** [comment]
> I used the bulk ops to delete all "Article (deprecated)" nodes and it seems to unblock the config import.

That should have be done be the other PR, will keep an eye on dev

**Comment by rupl** [comment]
I did it all on my local, nothing done to dev yet:

- Checked out #58 - `composer install`, `updb`, `cim`
- Checked out this PR - bulk delete, `cim`

**Pull request merged**
